"""Add embedding column

Revision ID: 9d53added2b9
Revises: a6ef054821a5
Create Date: 2026-03-18 20:56:57.852927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '9d53added2b9'
down_revision: Union[str, None] = 'a6ef054821a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garments', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1024), nullable=True, comment='Signature sémantique du vêtement (générée par Mistral AI)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('garments', 'embedding')
    # ### end Alembic commands ###
